//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18408
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;


		public class TargetAble : MonoBehaviour
		{

			public float health = 0.0f;

			protected Transform target = null;

		    public string targetAbleColor = "";

			public bool isDestroyed(){
				return health<=0.0f;
			}

			public virtual void doDamage(float damage, string damageColor)
			{
/*                Debug.Log("doDamage damageColor=" + damageColor);
                Debug.Log("doDamage targetAbleColor=" + targetAbleColor);*/
                if (String.Equals(damageColor, targetAbleColor))
                {
                    //Debug.Log("doDamage RIGHT COLOR");
                    health -= damage;                  
                }
                /*
                if (damageColor.Equals(targetAbleColor)) {
				    health-=damage;
                }*/

				if(health<0){
					health = 0;
				}
			}
			
			public virtual void targeting(Transform attacker){}

		}


